### ISSUE TITLE
Docker compatibility?

### ISSUE THREAD

**Issue by apolloclark** [ansible-community/ansible-vault#114]
I'm trying to run this against an Ubuntu 18.04 Bionic docker image, and the task run is failing:

```
    docker: TASK [brianshumate.vault : Get Vault package checksum file (local)] ************
    docker: fatal: [default -> vault-1.2.2-ubuntu18.04-20190829]: FAILED! => {"changed": false, "checksum_dest": null, "checksum_src": "65c329ae1c44ac95418d2b9e27283b81bedf1bce", "dest": "/home/apollo/Sites/packer-vault/base/ansible/roles/brianshumate.vault/files/vault_1.2.2_SHA256SUMS", "elapsed": 0, "msg": "Destination /home/apollo/Sites/packer-vault/base/ansible/roles/brianshumate.vault/files does not exist", "src": "/root/.ansible/tmp/ansible-tmp-1567100043.86-85675163808120/tmpCmRs2N", "url": "https://releases.hashicorp.com/vault/1.2.2/vault_1.2.2_SHA256SUMS"}
```

I confirmed the folder does exist, and set the chmod to 0777, the build it still failing.

Is this compatible with Docker? Maybe I could create a Pull Request, add a feature flag to the Ansible task to allow configuring the SHASUM check to run within the container?

**Comment by apolloclark** [comment]
Ok.. figured out that I can get further in the Ansible task run if I set:
```
vault_install_remotely: true
```
Now I'm hitting the error:
```
    docker: TASK [brianshumate.vault : Check Vault mlock capability] ***********************
    docker: fatal: [default]: FAILED! => {"changed": false, "cmd": "setcap cap_ipc_lock=+ep /usr/local/bin/vault", "msg": "[Errno 2] No such file or directory", "rc": 2}
    docker: ...ignoring
    docker:
    docker: TASK [brianshumate.vault : Enable non root mlock capability] *******************
    docker: fatal: [default]: FAILED! => {"changed": false, "cmd": "setcap cap_ipc_lock=+ep /usr/local/bin/vault", "msg": "[Errno 2] No such file or directory", "rc": 2}
```
Seems related to https://github.com/hashicorp/docker-vault/issues/39 and https://github.com/hashicorp/docker-vault/issues/53 and https://github.com/hashicorp/docker-vault/issues/89 and https://github.com/hashicorp/docker-vault/pull/126

**Comment by apolloclark** [comment]
Ok... read over the docs at: https://hub.docker.com/_/vault

They mention needing to modify the docker run command, by adding:
```
docker run --cap-add=IPC_LOCK vault
```

Noticed the default ubuntu:18.04 image is missing the "setcap" command, fixed that with:
```
apt-get install -y libcap2-bin
```
then got this error:
```
    docker: TASK [brianshumate.vault : Vault main configuration] ***************************
    docker: fatal: [default]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible_default_ipv4' is undefined"}
```
Related to https://github.com/ansible/molecule/issues/836 and fixed with:
```
apt-get install -y iproute2
```
now the Ansible run is failing at the final step:
```
    docker: TASK [brianshumate.vault : Vault API reachable?] *******************************
    docker: FAILED - RETRYING: Vault API reachable? (30 retries left).
...
    docker: fatal: [default]: FAILED! => {"attempts": 30, "changed": false, "content": "", "elapsed": 0, "msg": "Status code was -1 and not [200, 429, 473, 501, 503]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://172.17.0.2:8200/v1/sys/health"}
    docker:

```
I'm guessing it's because of Ansible trying to run "/sbin/initctl" within a Docker image:
```
    docker: TASK [brianshumate.vault : Debian init script] *********************************
    docker: changed: [default][2m 49s]

    docker: TASK [brianshumate.vault : extract systemd version] ****************************
    docker: skipping: [default]
```
I've dealt with this in the past by either adding a feature flag to the Ansible task to not run systemd service tasks, or install the [docker-systemctl-replacement](https://github.com/gdraheim/docker-systemctl-replacement). I'll see if I can somehow trick Ansible into running the docker-systemctl-replacement...

https://github.com/ansible/ansible/blob/stable-2.8/lib/ansible/modules/system/service.py#L426

I was able to "trick" Ansible into thinking it's a systemd environment by building the Docker images with:
```
RUN cd /tmp \
  && curl -sLO https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl.py \
  && yes | cp -f systemctl.py /usr/bin/systemctl \
  && chmod a+x /usr/bin/systemctl \
  && mkdir -p /run/systemd/system/ \
  && rm -rf /sbin/initctl
```
I'm seeing this in the Vault service log:
```
root@e79e044b8d14:/var/log# grep -inr 'vault'
journal/vault.service.log:4:2019-08-29T21:58:01.510Z [WARN]  storage migration check error: error="Get http://127.0.0.1:8500/v1/kv/vault/core/migration: dial tcp 127.0.0.1:8500: connect: connection refused"
```
tried debugging the vault config:
```
# cat /etc/vault.d/vault_main.hcl
cluster_name = "dc1"
max_lease_ttl = "768h"
default_lease_ttl = "768h"

disable_clustering = "False"
cluster_addr = "http://172.17.0.2:8201"
api_addr = "http://172.17.0.2:8200"

plugin_directory = "/usr/local/lib/vault/plugins"

listener "tcp" {
  address = "172.17.0.2:8200"
  cluster_address = "172.17.0.2:8201"
  tls_disable = "true"
}

backend "consul" {
  address = "127.0.0.1:8500"
  path = "vault"
  service = "vault"
    scheme = "http"
  }
ui = true
```
I'll try setting the backend to "file"... here's the new syslog:
```
2019-08-29T22:27:19.605Z [INFO]  core: security barrier not initialized
```
