### ISSUE TITLE
Where is the 2.5.3 release?

### ISSUE THREAD

**Issue by erinn** [ansible-community/ansible-vault#165]
I see it tagged here, I see it moved from Brian's repo, I do not see it in ansible galaxy, am I missing something?

Thanks,
-Erinn

**Comment by bbaassssiiee** [comment]
Thanks for your report. Brian Shumate handed a couple of ansible roles over to the community because he is doing other things at work. I moved the repo's into https://github.com/ansible-community and have yet find a way to push from there to Galaxy.

Meanwhile you can pull this version using a `requirements.yml` file like this:

```yaml
- src: https://github.com/ansible-community/ansible-vault.git
  name: ansible-community/ansible-vault
  scm: git
  version: v2.5.3
```

**Comment by willhaines** [comment]
Thanks for the workaround, @bbaassssiiee. In case anyone else stumbles on this issue, I did have to add a "v" in front of the version to make `ansible-galaxy install -r requirements.yml` happy:

```yaml
- src: https://github.com/ansible-community/ansible-vault.git
  name: ansible-community/ansible-vault
  scm: git
  version: v2.5.3
```
