### ISSUE TITLE
Task "Copy over GCP Credentials for Auto Unseal" Never Executes

### ISSUE THREAD

**Issue by brektyme** [ansible-community/ansible-vault#248]
```
- name: "Copy over GCP Credentials for Auto Unseal"
  copy:
    src: "{{ vault_gkms_credentials_src_file }}"
    dest: "{{ vault_gkms_credentials }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "0600"
  when: vault_gkms_credentials_src_file | length | bool
```

This conditional never evaluates to true even when `vault_gkms_credentials_src_file` is set.

output from ansible-inventory showing value of `vault_gkms_credentials_src_file`:
```
"vault_gkms_credentials_src_file": "/tmp/GCP_CRED"
```

results from playbook run:
```
TASK [vault : Copy over GCP Credentials for Auto Unseal] ****************************************************************************************************************************************************
task path: ansible/roles/vault/tasks/main.yml:137
skipping: [vault0] => {
    "changed": false,
    "skip_reason": "Conditional result was False"
}
```
