### ISSUE TITLE
Odd use of with_fileglob

### ISSUE THREAD

**Issue by schmiddy** [ansible-community/ansible-vault#40]
Hi,

I happened to notice an odd complaint like this from `ansible-review` in some code that included this role.

```
ERROR: Standard "bare words are deprecated for with_items" not met:
./vault/tasks/install_remote.yml:61: [ANSIBLE0015] Found a bare variable '/tmp/vault' used in a 'with_fileglob' loop. You should use the full variable syntax ('{{/tmp/vault}}')
```

This error seems to be complaining about [this line](https://github.com/brianshumate/ansible-vault/blob/49dac6b751ab5c21a0bb9eb684971654d42e4d73/tasks/install_remote.yml#L62). Is there any reason to use `with_fileglob:` here (apparently to delete that entire directory, without using any `*` wildcard) ? Why not just something like:

```
- name: Cleanup
  file:
    path: "/tmp/vault"
    state: absent
  tags: installation
```
