### ISSUE TITLE
Vault wont start due to AmbientCapabilities in Systemd unit file

### ISSUE THREAD

**Issue by jeffWelling** [ansible-community/ansible-vault#67]
In version v2.0.7 of this role, the systemd unit file includes the following line:

AmbientCapabilities=CAP_SYSLOG CAP_IPC_LOCK

However, on a Centos7 host running Linux 3.10.0-693.11.1.el7.x86_64 with systemd 219, this causes vault to fail to start with the following log message:

    systemd[20617]: Failed at step CAPABILITIES spawning /usr/local/bin/vault: Operation not permitted

Removing this line allows systemd to start.

It sounds to me like the playbook should only attempt to include that line if the software version supports it, perhaps this should be wrapped in a conditional check instead of being included on every system. 

Note: Yum shows no pending upgrades available for this system, so I don't think this can be solved with a yum upgrade.

**Comment by jeffWelling** [comment]
@bdossantos if I'm correct that you added this bit, is there any chance you'll have time to track down which version this works with and to add a conditional so that it doesn't cause breakage? Apologies if it wasn't you that added that line, I'm just going off of git blame :)

**Comment by bdossantos** [comment]
Hi,

Sorry for the breakage.

Systemd >=230 is required for this directive to work (see changelog linked in #65)

Maybe the quick (but not perfect) way to fix this is to extract systemd version to do the condition

``` 
$ systemctl --version systemd
systemd 215
+PAM +AUDIT +SELINUX +IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ -SECCOMP -APPARMOR
```

```
$ systemctl --version systemd | head -n 1 | cut -d' ' -f2
215
```

```yaml
- name: extract systemd version
  shell: systemctl --version systemd | head -n 1 | cut -d' ' -f2
  register: systemd_version
  when:
    - ansible_service_mgr == "systemd"
    - not ansible_os_family == "FreeBSD"
    - not ansible_os_family == "Solaris"
```
