### ISSUE TITLE
connection refuse to 

### ISSUE THREAD

**Issue by zakabluk** [ansible-community/ansible-vault#78]
I have installed role on Debian 9.
My playbook contains:
---
```
- name: Converge
  hosts: vault
  roles:
    - { role: '/opt/git/hq_gitlab/ansible-vault' }
  vars:
      vault_version: 1.0.2
      vault_iface: ens18
      vault_ui: true
      vault_cluster_disable: true
```
But after installation was failed task "Vault API reachable?" 
In log vault I saw messages 
` storage migration check error: error="Get http://127.0.0.1:8500/v1/kv/vault/core/migration: dial tcp 127.0.0.1:8500: connect: connection`
